Imports System
Imports System.IO
Imports System.Text
Imports System.Globalization
Imports System.Configuration
Imports System.Data
Imports System.Data.Sqlite

Public Class SticsTempoparConverter
    
    Inherits Converter
    
    Public Overrides Sub Export(DirectoryPath As String)
    End Sub

    Public Overrides Sub Export(
            DirectoryPath As String,
            MasterInput_Connection As SqliteConnection,
            ModelDictionary_Connection As SqliteConnection)

        Dim fileName As String = "tempopar.sti"
        Dim fileContent As StringBuilder = New StringBuilder()

        Dim ST(8) As String
        ST = DirectoryPath.Split(Path.DirectorySeparatorChar)
        DirectoryPath = ST(0) & Path.DirectorySeparatorChar & ST(1) & Path.DirectorySeparatorChar & ST(2) & Path.DirectorySeparatorChar & ST(3) & Path.DirectorySeparatorChar & ST(4) & Path.DirectorySeparatorChar & ST(5) & Path.DirectorySeparatorChar & ST(6) & Path.DirectorySeparatorChar & ST(7)
        'Tempopar query
        Dim T As String = "Select   Champ, Default_Value_Datamill, defaultValueOtherSource, IFNULL([defaultValueOtherSource],  [Default_Value_Datamill]) As dv From Variables Where ((model='stics') AND ([Table]='st_tempopar')) OR ((model='stics') AND ([Table]='st_tempopar_2')) OR ((model='stics') AND ([Table]='st_tempopar_3'));"
        Dim DT As New DataSet()
        Dim row As DataRow
        Dim Cmd As New SqliteDataAdapter(T, ModelDictionary_Connection)
        Cmd.Fill(DT, "TChamp")
        Dim fetchAllQuery As String = "SELECT SimUnitList.idsim, SimulationOptions.StressW_YN, SimulationOptions.StressN_YN, SimulationOptions.StressP_YN, SimulationOptions.StressK_YN " _
        & "FROM SimUnitList INNER JOIN SimulationOptions ON SimUnitList.IdOption = SimulationOptions.IdOptions Where idsim ='" + ST(7) + "';"
        Dim DA = New SqliteDataAdapter(fetchAllQuery, MasterInput_Connection)
        'MsgBox(fetchAllQuery)
        ' Filling Dataset
        Dim DSTrav As New DataSet()
        DA.Fill(DSTrav)
        Dim DTable As DataTable = DSTrav.Tables(0)
        row = DTable.Rows(0)
        fileContent.AppendLine("codeinnact")
        If row.Item("StressN_YN") Then
            fileContent.AppendLine("1")
        Else
            fileContent.AppendLine("2")
        End If
        'fileContent.AppendLine(row.Item("StressN_YN"))
        'FormatSticsData(fileContent, DT, "codeinnact")
        fileContent.AppendLine("codeh2oact")
        If row.Item("StressW_YN") Then
            fileContent.AppendLine("1")
        Else
            fileContent.AppendLine("2")
        End If
        'fileContent.AppendLine(row.Item("StressW_YN"))
        'FormatSticsData(fileContent, DT, "codeh2oact")
        FormatSticsData(fileContent, DT, "codeminopt")
        FormatSticsData(fileContent, DT, "iniprofil")
        FormatSticsData(fileContent, DT, "codeprofmes")
        FormatSticsData(fileContent, DT, "codeinitprec")
        FormatSticsData(fileContent, DT, "codemsfinal")
        FormatSticsData(fileContent, DT, "codeactimulch")
        FormatSticsData(fileContent, DT, "codefrmur")
        FormatSticsData(fileContent, DT, "codemicheur")
        FormatSticsData(fileContent, DT, "codeoutscient")
        FormatSticsData(fileContent, DT, "codeseprapport")
        FormatSticsData(fileContent, DT, "separateurrapport")
        FormatSticsData(fileContent, DT, "codesensibilite")
        FormatSticsData(fileContent, DT, "codesnow")
        FormatSticsData(fileContent, DT, "flagecriture")
        FormatSticsData(fileContent, DT, "parsurrg")
        FormatSticsData(fileContent, DT, "coefb")
        FormatSticsData(fileContent, DT, "proprac")
        FormatSticsData(fileContent, DT, "y0msrac")
        FormatSticsData(fileContent, DT, "khaut")
        FormatSticsData(fileContent, DT, "dacohes")
        FormatSticsData(fileContent, DT, "daseuilbas")
        FormatSticsData(fileContent, DT, "daseuilhaut")
        FormatSticsData(fileContent, DT, "beta")
        FormatSticsData(fileContent, DT, "lvopt")
        FormatSticsData(fileContent, DT, "rayon")
        FormatSticsData(fileContent, DT, "difN")
        FormatSticsData(fileContent, DT, "concrr")
        FormatSticsData(fileContent, DT, "plNmin")
        FormatSticsData(fileContent, DT, "irrlev")
        FormatSticsData(fileContent, DT, "QNpltminINN")
        FormatSticsData(fileContent, DT, "codesymbiose")
        FormatSticsData(fileContent, DT, "codefxn")
        FormatSticsData(fileContent, DT, "FTEMh")
        FormatSticsData(fileContent, DT, "FTEMha")
        FormatSticsData(fileContent, DT, "TREFh")
        FormatSticsData(fileContent, DT, "FTEMr")
        FormatSticsData(fileContent, DT, "FTEMra")
        FormatSticsData(fileContent, DT, "TREFr")
        FormatSticsData(fileContent, DT, "FINERT")
        FormatSticsData(fileContent, DT, "FMIN1")
        FormatSticsData(fileContent, DT, "FMIN2")
        FormatSticsData(fileContent, DT, "FMIN3")
        FormatSticsData(fileContent, DT, "Wh")
        FormatSticsData(fileContent, DT, "pHminvol")
        FormatSticsData(fileContent, DT, "pHmaxvol")
        FormatSticsData(fileContent, DT, "Vabs2")
        FormatSticsData(fileContent, DT, "Xorgmax")
        FormatSticsData(fileContent, DT, "hminm")
        FormatSticsData(fileContent, DT, "hoptm")
        FormatSticsData(fileContent, DT, "alphaph")
        FormatSticsData(fileContent, DT, "dphvolmax")
        FormatSticsData(fileContent, DT, "phvols")
        FormatSticsData(fileContent, DT, "fhminsat")
        FormatSticsData(fileContent, DT, "fredkN")
        FormatSticsData(fileContent, DT, "fredlN")
        FormatSticsData(fileContent, DT, "fNCbiomin")
        FormatSticsData(fileContent, DT, "fredNsup")
        FormatSticsData(fileContent, DT, "Primingmax")
        FormatSticsData(fileContent, DT, "hminn")
        FormatSticsData(fileContent, DT, "hoptn")
        FormatSticsData(fileContent, DT, "pHminnit")
        FormatSticsData(fileContent, DT, "pHmaxnit")
        FormatSticsData(fileContent, DT, "nh4_min")
        FormatSticsData(fileContent, DT, "pHminden")
        FormatSticsData(fileContent, DT, "pHmaxden")
        FormatSticsData(fileContent, DT, "wfpsc")
        FormatSticsData(fileContent, DT, "tdenitopt_gauss")
        FormatSticsData(fileContent, DT, "scale_tdenitopt")
        FormatSticsData(fileContent, DT, "Kd")
        FormatSticsData(fileContent, DT, "k_desat")
        FormatSticsData(fileContent, DT, "code_vnit")
        FormatSticsData(fileContent, DT, "fnx")
        FormatSticsData(fileContent, DT, "vnitmax")
        FormatSticsData(fileContent, DT, "Kamm")
        FormatSticsData(fileContent, DT, "code_tnit")
        FormatSticsData(fileContent, DT, "tnitmin")
        FormatSticsData(fileContent, DT, "tnitopt")
        FormatSticsData(fileContent, DT, "tnitopt2")
        FormatSticsData(fileContent, DT, "tnitmax")
        FormatSticsData(fileContent, DT, "tnitopt_gauss")
        FormatSticsData(fileContent, DT, "scale_tnitopt")
        FormatSticsData(fileContent, DT, "code_rationit")
        FormatSticsData(fileContent, DT, "rationit", 6)
        FormatSticsData(fileContent, DT, "code_hourly_wfps_nit")
        FormatSticsData(fileContent, DT, "code_pdenit")
        FormatSticsData(fileContent, DT, "cmin_pdenit")
        FormatSticsData(fileContent, DT, "cmax_pdenit")
        FormatSticsData(fileContent, DT, "min_pdenit")
        FormatSticsData(fileContent, DT, "max_pdenit")
        FormatSticsData(fileContent, DT, "code_ratiodenit")
        FormatSticsData(fileContent, DT, "ratiodenit")
        FormatSticsData(fileContent, DT, "code_hourly_wfps_denit")
        FormatSticsData(fileContent, DT, "pminruis")
        FormatSticsData(fileContent, DT, "diftherm")
        FormatSticsData(fileContent, DT, "bformnappe")
        FormatSticsData(fileContent, DT, "rdrain")
        FormatSticsData(fileContent, DT, "psihumin")
        FormatSticsData(fileContent, DT, "psihucc")
        FormatSticsData(fileContent, DT, "prophumtasssem")
        FormatSticsData(fileContent, DT, "prophumtassrec")
        FormatSticsData(fileContent, DT, "codhnappe")
        FormatSticsData(fileContent, DT, "distdrain", 2, 0)
        FormatSticsData(fileContent, DT, "proflabour")
        FormatSticsData(fileContent, DT, "proftravmin")
        FormatSticsData(fileContent, DT, "codetycailloux")
        FormatSticsData(fileContent, DT, "masvolcx", 5, 1)
        FormatSticsData(fileContent, DT, "hcccx", 5, 1)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 2)
        FormatSticsData(fileContent, DT, "hcccx", 5, 2)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 3)
        FormatSticsData(fileContent, DT, "hcccx", 5, 3)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 4)
        FormatSticsData(fileContent, DT, "hcccx", 5, 4)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 5)
        FormatSticsData(fileContent, DT, "hcccx", 5, 5)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 6)
        FormatSticsData(fileContent, DT, "hcccx", 5, 6)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 7)
        FormatSticsData(fileContent, DT, "hcccx", 5, 7)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 8)
        FormatSticsData(fileContent, DT, "hcccx", 5, 8)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 9)
        FormatSticsData(fileContent, DT, "hcccx", 5, 9)
        FormatSticsData(fileContent, DT, "masvolcx", 5, 10)
        FormatSticsData(fileContent, DT, "hcccx", 5, 10)
        FormatSticsData(fileContent, DT, "codetypeng")
        FormatSticsData(fileContent, DT, "engamm", 5, 1)
        FormatSticsData(fileContent, DT, "orgeng", 5, 1)
        FormatSticsData(fileContent, DT, "deneng", 5, 1)
        FormatSticsData(fileContent, DT, "voleng", 5, 1)
        FormatSticsData(fileContent, DT, "engamm", 5, 2)
        FormatSticsData(fileContent, DT, "orgeng", 5, 2)
        FormatSticsData(fileContent, DT, "deneng", 5, 2)
        FormatSticsData(fileContent, DT, "voleng", 5, 2)
        FormatSticsData(fileContent, DT, "engamm", 5, 3)
        FormatSticsData(fileContent, DT, "orgeng", 5, 3)
        FormatSticsData(fileContent, DT, "deneng", 5, 3)
        FormatSticsData(fileContent, DT, "voleng", 5, 3)
        FormatSticsData(fileContent, DT, "engamm", 5, 4)
        FormatSticsData(fileContent, DT, "orgeng", 5, 4)
        FormatSticsData(fileContent, DT, "deneng", 5, 4)
        FormatSticsData(fileContent, DT, "voleng", 5, 4)
        FormatSticsData(fileContent, DT, "engamm", 5, 5)
        FormatSticsData(fileContent, DT, "orgeng", 5, 5)
        FormatSticsData(fileContent, DT, "deneng", 5, 5)
        FormatSticsData(fileContent, DT, "voleng", 5, 5)
        FormatSticsData(fileContent, DT, "engamm", 5, 6)
        FormatSticsData(fileContent, DT, "orgeng", 5, 6)
        FormatSticsData(fileContent, DT, "deneng", 5, 6)
        FormatSticsData(fileContent, DT, "voleng", 5, 6)
        FormatSticsData(fileContent, DT, "engamm", 5, 7)
        FormatSticsData(fileContent, DT, "orgeng", 5, 7)
        FormatSticsData(fileContent, DT, "deneng", 5, 7)
        FormatSticsData(fileContent, DT, "voleng", 5, 7)
        FormatSticsData(fileContent, DT, "engamm", 5, 8)
        FormatSticsData(fileContent, DT, "orgeng", 5, 8)
        FormatSticsData(fileContent, DT, "deneng", 5, 8)
        FormatSticsData(fileContent, DT, "voleng", 5, 8)
        FormatSticsData(fileContent, DT, "codetypres")

        FormatSticsData(fileContent, DT, "CroCo", 5, 1)
        FormatSticsData(fileContent, DT, "akres", 5, 1)
        FormatSticsData(fileContent, DT, "bkres", 5, 1)
        FormatSticsData(fileContent, DT, "awb", 5, 1)
        FormatSticsData(fileContent, DT, "bwb", 5, 1)
        FormatSticsData(fileContent, DT, "cwb", 5, 1)
        FormatSticsData(fileContent, DT, "ahres", 5, 1)
        FormatSticsData(fileContent, DT, "bhres", 5, 1)
        FormatSticsData(fileContent, DT, "kbio", 5, 1)
        FormatSticsData(fileContent, DT, "yres", 5, 1)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 1)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 1)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 1)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 1)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 1)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 1)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 1)

        FormatSticsData(fileContent, DT, "CroCo", 5, 2)
        FormatSticsData(fileContent, DT, "akres", 5, 2)
        FormatSticsData(fileContent, DT, "bkres", 5, 2)
        FormatSticsData(fileContent, DT, "awb", 5, 2)
        FormatSticsData(fileContent, DT, "bwb", 5, 2)
        FormatSticsData(fileContent, DT, "cwb", 5, 2)
        FormatSticsData(fileContent, DT, "ahres", 5, 2)
        FormatSticsData(fileContent, DT, "bhres", 5, 2)
        FormatSticsData(fileContent, DT, "kbio", 5, 2)
        FormatSticsData(fileContent, DT, "yres", 5, 2)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 2)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 2)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 2)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 2)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 2)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 2)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 2)

        FormatSticsData(fileContent, DT, "CroCo", 5, 3)
        FormatSticsData(fileContent, DT, "akres", 5, 3)
        FormatSticsData(fileContent, DT, "bkres", 5, 3)
        FormatSticsData(fileContent, DT, "awb", 5, 3)
        FormatSticsData(fileContent, DT, "bwb", 5, 3)
        FormatSticsData(fileContent, DT, "cwb", 5, 3)
        FormatSticsData(fileContent, DT, "ahres", 5, 3)
        FormatSticsData(fileContent, DT, "bhres", 5, 3)
        FormatSticsData(fileContent, DT, "kbio", 5, 3)
        FormatSticsData(fileContent, DT, "yres", 5, 3)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 3)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 3)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 3)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 3)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 3)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 3)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 3)

        FormatSticsData(fileContent, DT, "CroCo", 5, 4)
        FormatSticsData(fileContent, DT, "akres", 5, 4)
        FormatSticsData(fileContent, DT, "bkres", 5, 4)
        FormatSticsData(fileContent, DT, "awb", 5, 4)
        FormatSticsData(fileContent, DT, "bwb", 5, 4)
        FormatSticsData(fileContent, DT, "cwb", 5, 4)
        FormatSticsData(fileContent, DT, "ahres", 5, 4)
        FormatSticsData(fileContent, DT, "bhres", 5, 4)
        FormatSticsData(fileContent, DT, "kbio", 5, 4)
        FormatSticsData(fileContent, DT, "yres", 5, 4)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 4)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 4)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 4)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 4)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 4)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 4)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 4)

        FormatSticsData(fileContent, DT, "CroCo", 5, 5)
        FormatSticsData(fileContent, DT, "akres", 5, 5)
        FormatSticsData(fileContent, DT, "bkres", 5, 5)
        FormatSticsData(fileContent, DT, "awb", 5, 5)
        FormatSticsData(fileContent, DT, "bwb", 5, 5)
        FormatSticsData(fileContent, DT, "cwb", 5, 5)
        FormatSticsData(fileContent, DT, "ahres", 5, 5)
        FormatSticsData(fileContent, DT, "bhres", 5, 5)
        FormatSticsData(fileContent, DT, "kbio", 5, 5)
        FormatSticsData(fileContent, DT, "yres", 5, 5)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 5)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 5)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 5)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 5)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 5)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 5)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 5)

        FormatSticsData(fileContent, DT, "CroCo", 5, 6)
        FormatSticsData(fileContent, DT, "akres", 5, 6)
        FormatSticsData(fileContent, DT, "bkres", 5, 6)
        FormatSticsData(fileContent, DT, "awb", 5, 6)
        FormatSticsData(fileContent, DT, "bwb", 5, 6)
        FormatSticsData(fileContent, DT, "cwb", 5, 6)
        FormatSticsData(fileContent, DT, "ahres", 5, 6)
        FormatSticsData(fileContent, DT, "bhres", 5, 6)
        FormatSticsData(fileContent, DT, "kbio", 5, 6)
        FormatSticsData(fileContent, DT, "yres", 5, 6)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 6)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 6)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 6)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 6)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 6)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 6)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 6)

        FormatSticsData(fileContent, DT, "CroCo", 5, 7)
        FormatSticsData(fileContent, DT, "akres", 5, 7)
        FormatSticsData(fileContent, DT, "bkres", 5, 7)
        FormatSticsData(fileContent, DT, "awb", 5, 7)
        FormatSticsData(fileContent, DT, "bwb", 5, 7)
        FormatSticsData(fileContent, DT, "cwb", 5, 7)
        FormatSticsData(fileContent, DT, "ahres", 5, 7)
        FormatSticsData(fileContent, DT, "bhres", 5, 7)
        FormatSticsData(fileContent, DT, "kbio", 5, 7)

        FormatSticsData(fileContent, DT, "yres", 5, 7)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 7)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 7)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 7)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 7)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 7)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 7)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 7)

        FormatSticsData(fileContent, DT, "CroCo", 5, 8)
        FormatSticsData(fileContent, DT, "akres", 5, 8)
        FormatSticsData(fileContent, DT, "bkres", 5, 8)
        FormatSticsData(fileContent, DT, "awb", 5, 8)
        FormatSticsData(fileContent, DT, "bwb", 5, 8)
        FormatSticsData(fileContent, DT, "cwb", 5, 8)
        FormatSticsData(fileContent, DT, "ahres", 5, 8)
        FormatSticsData(fileContent, DT, "bhres", 5, 8)
        FormatSticsData(fileContent, DT, "kbio", 5, 8)
        FormatSticsData(fileContent, DT, "yres", 5, 8)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 8)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 8)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 8)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 8)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 8)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 8)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 8)

        FormatSticsData(fileContent, DT, "CroCo", 5, 9)
        FormatSticsData(fileContent, DT, "akres", 5, 9)
        FormatSticsData(fileContent, DT, "bkres", 5, 9)
        FormatSticsData(fileContent, DT, "awb", 5, 9)
        FormatSticsData(fileContent, DT, "bwb", 5, 9)
        FormatSticsData(fileContent, DT, "cwb", 5, 9)
        FormatSticsData(fileContent, DT, "ahres", 5, 9)
        FormatSticsData(fileContent, DT, "bhres", 5, 9)
        FormatSticsData(fileContent, DT, "kbio", 5, 9)
        FormatSticsData(fileContent, DT, "yres", 5, 9)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 9)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 9)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 9)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 9)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 9)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 9)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 9)

        FormatSticsData(fileContent, DT, "CroCo", 5, 10)
        FormatSticsData(fileContent, DT, "akres", 5, 10)
        FormatSticsData(fileContent, DT, "bkres", 5, 10)
        FormatSticsData(fileContent, DT, "awb", 5, 10)
        FormatSticsData(fileContent, DT, "bwb", 5, 10)
        FormatSticsData(fileContent, DT, "cwb", 5, 10)
        FormatSticsData(fileContent, DT, "ahres", 5, 10)
        FormatSticsData(fileContent, DT, "bhres", 5, 10)
        FormatSticsData(fileContent, DT, "kbio", 5, 10)
        FormatSticsData(fileContent, DT, "yres", 5, 10)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 10)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 10)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 10)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 10)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 10)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 10)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 10)

        FormatSticsData(fileContent, DT, "CroCo", 5, 11)
        FormatSticsData(fileContent, DT, "akres", 5, 11)
        FormatSticsData(fileContent, DT, "bkres", 5, 11)
        FormatSticsData(fileContent, DT, "awb", 5, 11)
        FormatSticsData(fileContent, DT, "bwb", 5, 11)
        FormatSticsData(fileContent, DT, "cwb", 5, 11)
        FormatSticsData(fileContent, DT, "ahres", 5, 11)
        FormatSticsData(fileContent, DT, "bhres", 5, 11)
        FormatSticsData(fileContent, DT, "kbio", 5, 11)
        FormatSticsData(fileContent, DT, "yres", 5, 11)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 11)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 11)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 11)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 11)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 11)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 11)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 11)

        FormatSticsData(fileContent, DT, "CroCo", 5, 12)
        FormatSticsData(fileContent, DT, "akres", 5, 12)
        FormatSticsData(fileContent, DT, "bkres", 5, 12)
        FormatSticsData(fileContent, DT, "awb", 5, 12)
        FormatSticsData(fileContent, DT, "bwb", 5, 12)
        FormatSticsData(fileContent, DT, "cwb", 5, 12)
        FormatSticsData(fileContent, DT, "ahres", 5, 12)
        FormatSticsData(fileContent, DT, "bhres", 5, 12)
        FormatSticsData(fileContent, DT, "kbio", 5, 12)
        FormatSticsData(fileContent, DT, "yres", 5, 12)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 12)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 12)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 12)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 12)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 12)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 12)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 12)

        FormatSticsData(fileContent, DT, "CroCo", 5, 13)
        FormatSticsData(fileContent, DT, "akres", 5, 13)
        FormatSticsData(fileContent, DT, "bkres", 5, 13)
        FormatSticsData(fileContent, DT, "awb", 5, 13)
        FormatSticsData(fileContent, DT, "bwb", 5, 13)
        FormatSticsData(fileContent, DT, "cwb", 5, 13)
        FormatSticsData(fileContent, DT, "ahres", 5, 13)
        FormatSticsData(fileContent, DT, "bhres", 5, 13)
        FormatSticsData(fileContent, DT, "kbio", 5, 13)
        FormatSticsData(fileContent, DT, "yres", 5, 13)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 13)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 13)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 13)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 13)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 13)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 13)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 13)

        FormatSticsData(fileContent, DT, "CroCo", 5, 14)
        FormatSticsData(fileContent, DT, "akres", 5, 14)
        FormatSticsData(fileContent, DT, "bkres", 5, 14)
        FormatSticsData(fileContent, DT, "awb", 5, 14)
        FormatSticsData(fileContent, DT, "bwb", 5, 14)
        FormatSticsData(fileContent, DT, "cwb", 5, 14)
        FormatSticsData(fileContent, DT, "ahres", 5, 14)
        FormatSticsData(fileContent, DT, "bhres", 5, 14)
        FormatSticsData(fileContent, DT, "kbio", 5, 14)
        FormatSticsData(fileContent, DT, "yres", 5, 14)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 14)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 14)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 14)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 14)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 14)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 14)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 14)

        FormatSticsData(fileContent, DT, "CroCo", 5, 15)
        FormatSticsData(fileContent, DT, "akres", 5, 15)
        FormatSticsData(fileContent, DT, "bkres", 5, 15)
        FormatSticsData(fileContent, DT, "awb", 5, 15)
        FormatSticsData(fileContent, DT, "bwb", 5, 15)
        FormatSticsData(fileContent, DT, "cwb", 5, 15)
        FormatSticsData(fileContent, DT, "ahres", 5, 15)
        FormatSticsData(fileContent, DT, "bhres", 5, 15)
        FormatSticsData(fileContent, DT, "kbio", 5, 15)
        FormatSticsData(fileContent, DT, "yres", 5, 15)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 15)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 15)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 15)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 15)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 15)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 15)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 15)

        FormatSticsData(fileContent, DT, "CroCo", 5, 16)
        FormatSticsData(fileContent, DT, "akres", 5, 16)
        FormatSticsData(fileContent, DT, "bkres", 5, 16)
        FormatSticsData(fileContent, DT, "awb", 5, 16)
        FormatSticsData(fileContent, DT, "bwb", 5, 16)
        FormatSticsData(fileContent, DT, "cwb", 5, 16)
        FormatSticsData(fileContent, DT, "ahres", 5, 16)
        FormatSticsData(fileContent, DT, "bhres", 5, 16)
        FormatSticsData(fileContent, DT, "kbio", 5, 16)
        FormatSticsData(fileContent, DT, "yres", 5, 16)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 16)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 16)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 16)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 16)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 16)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 16)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 16)

        FormatSticsData(fileContent, DT, "CroCo", 5, 17)
        FormatSticsData(fileContent, DT, "akres", 5, 17)
        FormatSticsData(fileContent, DT, "bkres", 5, 17)
        FormatSticsData(fileContent, DT, "awb", 5, 17)
        FormatSticsData(fileContent, DT, "bwb", 5, 17)
        FormatSticsData(fileContent, DT, "cwb", 5, 17)
        FormatSticsData(fileContent, DT, "ahres", 5, 17)
        FormatSticsData(fileContent, DT, "bhres", 5, 17)
        FormatSticsData(fileContent, DT, "kbio", 5, 17)
        FormatSticsData(fileContent, DT, "yres", 5, 17)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 17)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 17)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 17)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 17)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 17)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 17)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 17)

        FormatSticsData(fileContent, DT, "CroCo", 5, 18)
        FormatSticsData(fileContent, DT, "akres", 5, 18)
        FormatSticsData(fileContent, DT, "bkres", 5, 18)
        FormatSticsData(fileContent, DT, "awb", 5, 18)
        FormatSticsData(fileContent, DT, "bwb", 5, 18)
        FormatSticsData(fileContent, DT, "cwb", 5, 18)
        FormatSticsData(fileContent, DT, "ahres", 5, 18)
        FormatSticsData(fileContent, DT, "bhres", 5, 18)
        FormatSticsData(fileContent, DT, "kbio", 5, 18)
        FormatSticsData(fileContent, DT, "yres", 5, 18)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 18)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 18)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 18)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 18)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 18)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 18)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 18)

        FormatSticsData(fileContent, DT, "CroCo", 5, 19)
        FormatSticsData(fileContent, DT, "akres", 5, 19)
        FormatSticsData(fileContent, DT, "bkres", 5, 19)
        FormatSticsData(fileContent, DT, "awb", 5, 19)
        FormatSticsData(fileContent, DT, "bwb", 5, 19)
        FormatSticsData(fileContent, DT, "cwb", 5, 19)
        FormatSticsData(fileContent, DT, "ahres", 5, 19)
        FormatSticsData(fileContent, DT, "bhres", 5, 19)
        FormatSticsData(fileContent, DT, "kbio", 5, 19)
        FormatSticsData(fileContent, DT, "yres", 5, 19)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 19)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 19)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 19)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 19)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 19)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 19)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 19)

        FormatSticsData(fileContent, DT, "CroCo", 5, 20)
        FormatSticsData(fileContent, DT, "akres", 5, 20)
        FormatSticsData(fileContent, DT, "bkres", 5, 20)
        FormatSticsData(fileContent, DT, "awb", 5, 20)
        FormatSticsData(fileContent, DT, "bwb", 5, 20)
        FormatSticsData(fileContent, DT, "cwb", 5, 20)
        FormatSticsData(fileContent, DT, "ahres", 5, 20)
        FormatSticsData(fileContent, DT, "bhres", 5, 20)
        FormatSticsData(fileContent, DT, "kbio", 5, 20)
        FormatSticsData(fileContent, DT, "yres", 5, 20)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 20)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 20)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 20)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 20)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 20)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 20)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 20)

        FormatSticsData(fileContent, DT, "CroCo", 5, 21)
        FormatSticsData(fileContent, DT, "akres", 5, 21)
        FormatSticsData(fileContent, DT, "bkres", 5, 21)
        FormatSticsData(fileContent, DT, "awb", 5, 21)
        FormatSticsData(fileContent, DT, "bwb", 5, 21)
        FormatSticsData(fileContent, DT, "cwb", 5, 21)
        FormatSticsData(fileContent, DT, "ahres", 5, 21)
        FormatSticsData(fileContent, DT, "bhres", 5, 21)
        FormatSticsData(fileContent, DT, "kbio", 5, 21)
        FormatSticsData(fileContent, DT, "yres", 5, 21)
        FormatSticsData(fileContent, DT, "CNresmin", 5, 21)
        FormatSticsData(fileContent, DT, "CNresmax", 5, 21)
        FormatSticsData(fileContent, DT, "qmulchruis0", 5, 21)
        FormatSticsData(fileContent, DT, "mouillabilmulch", 5, 21)
        FormatSticsData(fileContent, DT, "kcouvmlch", 5, 21)
        FormatSticsData(fileContent, DT, "albedomulchresidus", 5, 21)
        FormatSticsData(fileContent, DT, "Qmulchdec", 5, 21)

        Try
            ' Export file to specified directory
            WriteFile(DirectoryPath, fileName, fileContent.ToString())
        Catch ex As Exception
            MessageBox.Show("Error during writing file : " + ex.Message)
        End Try
    End Sub


    Public Sub FormatSticsData(ByRef fileContent As StringBuilder, ByRef row As Object, ByVal champ As String, Optional ByVal precision As Integer = 5, Optional ByVal fieldIt As Integer = 0)
        Dim res As String
        Dim typeData As String
        Dim rw() As DataRow
        Dim data As Object
        Dim fieldName As String

        fieldName = champ
        'For repeated fields, build field name 
        If (fieldIt <> 0) Then
            champ = champ + fieldIt.ToString()
        End If

        'fetch data
        rw = row.tables(0).select("Champ='" & champ & "'")
        data = rw(0)("dv")
        res = ""
        typeData = data.GetType().ToString()

        'if type is string or int
        If ((typeData = "System.String") Or (typeData = "System.Int32")) Then
            res = data.ToString()
        End If
        'if type is real
        If (typeData = "System.Single") Then
            Dim tmp As Single
            'Convert object to double
            tmp = Convert.ToDouble(data)
            If precision > 0 And precision < 7 Then
                res = FormatNumber(tmp, precision)
            Else
                res = tmp.ToString("0.###e+0", CultureInfo.InvariantCulture)
            End If
        End If
        'if cell is null
        If (typeData = "System.DBNull") Then
            res = ""
        End If
        'Print data in file
        fileContent.Append(fieldName)
        fileContent.AppendLine()
        fileContent.Append(res)
        fileContent.AppendLine()
    End Sub

    Public Overrides Sub Import(DirectoryPath As String, model As String)

    End Sub
End Class




